include filter function derivatives developed by Isabel Le and Julian…
qutech/filter_functions pull request #38
Opened 2020-10-01 13:39 UTC by JDTeske

Include filter function gradients implemented by Isabel Le under the supervision of Julian Teske. Refactored by Julian Teske

2020-10-05 18:59 UTC, thangleiter commented
Looks great! I have a few high-level questions and suggestions:

1. Do we really need to cache the derivatives in the `PulseSequence` object? You only need to evaluate the derivative once during optimization, right? As far as I can imagine, only if one wants to compute the derivative of the concatenation of gate operations caching is really required.
2. I implemented caching of intermediate elements of the computation of the control matrix (see [here](https://github.com/qutech/filter_functions/tree/feature/cache_intermediates)) for calculating second order terms. I think this is useful here as well since they are required for the derivative as well (in `gradient.control_matrix_at_timestep_derivative`) and here they are computed twice. 
3. Why pin `sparse<=0.11` in `setup.py`?

2020-10-06 07:58 UTC, JDTeske commented
Dear honorable Mr. Hangleiter,
thank you for your positive feedback. Let me answer these questions in utter most brevity.

1. No, its sufficient for my optimizers if the gradients are returned ones. You need to calculate the derivative in every iteration of the optimization. Yes that would be the only use case, I can think of.
-> suggestion: store gradient flag as class attribute in PulseSequence, which is by default set to FALSE
2. Sounds legit. I will investigate this issue ASAP! Are you refering to parts which you only implemented recently?
3. If this was implemented by my pull request then not by purpose.

What is the suggested workflow, if we imply changes? Will you outright reject this pull request and I file another one?

2020-10-06 11:52 UTC, thangleiter commented
> suggestion: store gradient flag as class attribute in PulseSequence, which is by default set to FALSE

What should the flag signify?

> Sounds legit. I will investigate this issue ASAP! Are you refering to parts which you only implemented recently?

Yes, see https://github.com/qutech/filter_functions/pull/39

> If this was implemented by my pull request then not by purpose.

Ok, then we can just take that out.

> What is the suggested workflow, if we imply changes? Will you outright reject this pull request and I file another one?

You can just add commits on your remote. This PR will be automatically updated.

2020-11-16 18:48 UTC, thangleiter requested changes

2020-11-16 18:48 UTC, thangleiter commented on README.md
> +hadamard.is_cached('F')
This change should be undone (I think something went wrong with merging here).

2020-11-16 18:48 UTC, thangleiter commented on README.md
> +spectrum = 1e-2/abs(omega)  # omega is symmetric about zero
Same here.

2020-11-16 18:48 UTC, thangleiter commented on filter_functions/gradient.py
> +        raise ValueError('Not fitting shape of S.')
This is functionality already provided by `numeric._get_integrand()`.

2020-11-16 18:48 UTC, thangleiter commented on filter_functions/gradient.py
> +    integrand = np.einsum('ao,atho->atho', S_all, deriv_F)
We should be able to use `numeric._get_integrand` here.

2020-11-17 14:46 UTC, thangleiter commented on filter_functions/gradient.py
> +        raise ValueError('Not fitting shape of S.')
Can be done at a later point when cleaning up. Not worth the effort for now.

2020-11-17 17:03 UTC, merged